//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellularAutomata.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpectedValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpectedValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CellularAutomata.UnitTests.ExpectedValues", typeof(ExpectedValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Cells&gt;
        ///  &lt;Cell left=&quot;10&quot; top=&quot;20&quot; /&gt;
        ///  &lt;Cell left=&quot;30&quot; top=&quot;40&quot; /&gt;
        ///  &lt;Cell left=&quot;50&quot; top=&quot;60&quot; /&gt;
        ///&lt;/Cells&gt;.
        /// </summary>
        internal static string CellCollection_GetXml {
            get {
                return ResourceManager.GetString("CellCollection_GetXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Pattern name=&quot;walker&quot;&gt;
        ///  &lt;Description&gt;desc&lt;/Description&gt;
        ///  &lt;Cells&gt;
        ///    &lt;Cell left=&quot;5&quot; top=&quot;10&quot; /&gt;
        ///    &lt;Cell left=&quot;6&quot; top=&quot;11&quot; /&gt;
        ///  &lt;/Cells&gt;
        ///&lt;/Pattern&gt;.
        /// </summary>
        internal static string Pattern_GetXml {
            get {
                return ResourceManager.GetString("Pattern_GetXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Patterns&gt;
        ///  &lt;Pattern name=&quot;walker&quot;&gt;
        ///    &lt;Description&gt;desc&lt;/Description&gt;
        ///    &lt;Cells&gt;
        ///      &lt;Cell left=&quot;10&quot; top=&quot;20&quot; /&gt;
        ///    &lt;/Cells&gt;
        ///  &lt;/Pattern&gt;
        ///  &lt;Pattern name=&quot;test&quot;&gt;
        ///    &lt;Description&gt;desc1&lt;/Description&gt;
        ///    &lt;Cells&gt;
        ///      &lt;Cell left=&quot;20&quot; top=&quot;30&quot; /&gt;
        ///    &lt;/Cells&gt;
        ///  &lt;/Pattern&gt;
        ///  &lt;Pattern name=&quot;test2&quot;&gt;
        ///    &lt;Description&gt;desc2&lt;/Description&gt;
        ///    &lt;Cells&gt;
        ///      &lt;Cell left=&quot;30&quot; top=&quot;40&quot; /&gt;
        ///    &lt;/Cells&gt;
        ///  &lt;/Pattern&gt;
        ///&lt;/Patterns&gt;.
        /// </summary>
        internal static string PatternCollection_GetXml {
            get {
                return ResourceManager.GetString("PatternCollection_GetXml", resourceCulture);
            }
        }
    }
}
