//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellularAutomata.Framework
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder",
        "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance",
            "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp =
                        new global::System.Resources.ResourceManager("CellularAutomata.Framework.ExceptionMessages",
                                                                     typeof (ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field must be added to the form definition first..
        /// </summary>
        internal static string CannotAddField
        {
            get { return ResourceManager.GetString("CannotAddField", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to An item with the same key &apos;{0}&apos; has already been added..
        /// </summary>
        internal static string CollItemExist
        {
            get { return ResourceManager.GetString("CollItemExist", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Item with key &apos;{0}&apos; does not exist in the collection..
        /// </summary>
        internal static string CollItemNotExist
        {
            get { return ResourceManager.GetString("CollItemNotExist", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Object cannot be parent on itself.
        /// </summary>
        internal static string CyclicParentReference
        {
            get { return ResourceManager.GetString("CyclicParentReference", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Directory do not exists..
        /// </summary>
        internal static string DirectoryNotFound
        {
            get { return ResourceManager.GetString("DirectoryNotFound", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to The string is null or empty..
        /// </summary>
        internal static string EmptyString
        {
            get { return ResourceManager.GetString("EmptyString", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field has being already added to thr form.
        /// </summary>
        internal static string FieldAlreadyAdded
        {
            get { return ResourceManager.GetString("FieldAlreadyAdded", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field has being already added to different section.
        /// </summary>
        internal static string FieldAlreadyAddedToSection
        {
            get { return ResourceManager.GetString("FieldAlreadyAddedToSection", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field already belongs to different form. Use Clone() method to add cloned field object or remove it first from the source form..
        /// </summary>
        internal static string FieldAlreadyHasParentForm
        {
            get { return ResourceManager.GetString("FieldAlreadyHasParentForm", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Form cannot be parent of field. Use ParentForm instead..
        /// </summary>
        internal static string FieldIncorrectParent
        {
            get { return ResourceManager.GetString("FieldIncorrectParent", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; does not exists..
        /// </summary>
        internal static string FileNotFound
        {
            get { return ResourceManager.GetString("FileNotFound", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; cannot be resolved. Please verify the spelling is correct or that the full type name is provided..
        /// </summary>
        internal static string InvalidType
        {
            get { return ResourceManager.GetString("InvalidType", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot find constructor..
        /// </summary>
        internal static string MissingConstructor
        {
            get { return ResourceManager.GetString("MissingConstructor", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type attribute does not exist on the element {0}..
        /// </summary>
        internal static string NoTypeAttribute
        {
            get { return ResourceManager.GetString("NoTypeAttribute", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type {0} from configuration could not be created..
        /// </summary>
        internal static string TypeCouldNotBeCreated
        {
            get { return ResourceManager.GetString("TypeCouldNotBeCreated", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not matches the type of &apos;{1}&apos; .
        /// </summary>
        internal static string TypeNotExpected
        {
            get { return ResourceManager.GetString("TypeNotExpected", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported type! Type must be bool, string, int32, int16, int64, double, decimal, DateTime and Byte Array.
        /// </summary>
        internal static string UnsupportedMappingType
        {
            get { return ResourceManager.GetString("UnsupportedMappingType", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported type for custom xml serialization! Type must be bool, string, int32, int16, int64, double, decimal, DateTime and Byte Array.
        /// </summary>
        internal static string UnsupportedTypeForSerialization
        {
            get { return ResourceManager.GetString("UnsupportedTypeForSerialization", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value must be negative or 0..
        /// </summary>
        internal static string ValueNegative
        {
            get { return ResourceManager.GetString("ValueNegative", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value must be positive or 0..
        /// </summary>
        internal static string ValuePositive
        {
            get { return ResourceManager.GetString("ValuePositive", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than 0 bytes..
        /// </summary>
        internal static string ValueZeroBytes
        {
            get { return ResourceManager.GetString("ValueZeroBytes", resourceCulture); }
        }
    }
}